/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SIZE } from "./components/awc-name/awc-name.types";
export namespace Components {
    interface AwcButton {
        /**
          * Button color
         */
        "color": 'blue' | 'green' | 'red' | 'black';
        /**
          * Margin top size
         */
        "margin": 'none' | 'xsmall' | 'small' | 'medium' | 'large';
        /**
          * Button size
         */
        "size": 'xsmall' | 'small' | 'medium' | 'large';
        /**
          * Button text
         */
        "text": string;
    }
    interface AwcName {
        /**
          * First name
         */
        "first": string;
        /**
          * Greeting
         */
        "greeting": string;
        /**
          * Has Greeting
         */
        "hasGreeting": boolean;
        /**
          * Has size button
         */
        "hasSizeButton": boolean;
        /**
          * Last name
         */
        "last": string;
        /**
          * Middle name
         */
        "middle": string;
        /**
          * Text size
         */
        "size": SIZE;
    }
}
declare global {
    interface HTMLAwcButtonElement extends Components.AwcButton, HTMLStencilElement {
    }
    var HTMLAwcButtonElement: {
        prototype: HTMLAwcButtonElement;
        new (): HTMLAwcButtonElement;
    };
    interface HTMLAwcNameElement extends Components.AwcName, HTMLStencilElement {
    }
    var HTMLAwcNameElement: {
        prototype: HTMLAwcNameElement;
        new (): HTMLAwcNameElement;
    };
    interface HTMLElementTagNameMap {
        "awc-button": HTMLAwcButtonElement;
        "awc-name": HTMLAwcNameElement;
    }
}
declare namespace LocalJSX {
    interface AwcButton {
        /**
          * Button color
         */
        "color"?: 'blue' | 'green' | 'red' | 'black';
        /**
          * Margin top size
         */
        "margin"?: 'none' | 'xsmall' | 'small' | 'medium' | 'large';
        /**
          * Button size
         */
        "size"?: 'xsmall' | 'small' | 'medium' | 'large';
        /**
          * Button text
         */
        "text"?: string;
    }
    interface AwcName {
        /**
          * First name
         */
        "first"?: string;
        /**
          * Greeting
         */
        "greeting"?: string;
        /**
          * Has Greeting
         */
        "hasGreeting"?: boolean;
        /**
          * Has size button
         */
        "hasSizeButton"?: boolean;
        /**
          * Last name
         */
        "last"?: string;
        /**
          * Middle name
         */
        "middle"?: string;
        /**
          * Text size
         */
        "size"?: SIZE;
    }
    interface IntrinsicElements {
        "awc-button": AwcButton;
        "awc-name": AwcName;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "awc-button": LocalJSX.AwcButton & JSXBase.HTMLAttributes<HTMLAwcButtonElement>;
            "awc-name": LocalJSX.AwcName & JSXBase.HTMLAttributes<HTMLAwcNameElement>;
        }
    }
}
